### ISSUE TITLE
Issue at InferenceFunctions.h during installing

### ISSUE THREAD

**Issue by alexjorguer** [ivaleraM/GLFM#4] opened 2019-10-08 09:25 UTC
Hi!

I've got an issue meanwhile I was trying to instal that library into MacOS High Sierra 10.13.6.

I've done my installation in that order:

1. Installing Xcode Version 10.1 (10B61)
2. Installing Qt 3.1.1 Mac x64
3. Installing Anaconda Nav 1.9.7 with Python 2.7

Then, I tried to install the library following the documentation:

1. Cloned: git clone https://github.com/ivaleraM/GLFM.git
2. cd GLFM/install
3. bash install_for_python.sh

Once I run install_for_python.sh, it starts to install missing libraries but it stops when building 'GLFM.cpp', it gives that error:
`gcc -fno-strict-aliasing -I/Users/***/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/***/anaconda2/lib/python2.7/site-packages -I/Users/***/anaconda2/include -I/Users/***/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/****/anaconda2/include/python2.7 -c GLFM.cpp -o build/temp.macosx-10.6-x86_64-2.7/GLFM.o -w
GLFM.cpp:3034:18: error: no matching function for call to 'IBPsampler_func'
  __pyx_v_Kest = IBPsampler_func(__pyx_v_missing, __pyx_v_X, __pyx_...
                 ^~~~~~~~~~~~~~~
./../core/InferenceFunctions.h:7:5: note: candidate function not viable:
      requires 22 arguments, but 21 were provided
int IBPsampler_func (double missing, gsl_matrix *X, char *C, gsl_ma...
    ^
1 error generated.`

Giving an error that explains that a function of InferenceFunctions.h (IBPSampler_func) requires 22 arguments but only 21 were provided.

How can I solve it?

**Comment by melaniefp** [comment] 2019-10-10 00:56
Thanks for reaching out! We have been able to reproduce the error, and soon will fix the error.

**Comment by melaniefp** [comment] 2019-10-11 01:53
Everything should be fixed now.

The error was caused by the addition of an additional feature (record likelihood values) that should have been under a development branch instead of master. We have rebased and isolated those problematic commits.

**Closed by melaniefp** 2019-10-11 01:54 UTC
